ignore_unreachable_actions:
  - ^campaigns/campaign_gift_options#create
  - ^campaigns/campaign_gift_options#update_order
  - ^campaigns/campaign_gift_options#destroy
  - ^campaigns/campaign_gift_options#show
  - ^campaigns/campaign_gift_options#report
  - ^campaigns/campaign_gift_options#update
  - ^nonprofits#onboard
  - ^devise#_prefixes
  - ^devise/confirmations#create
  - ^devise/confirmations#new
  - ^devise/confirmations#show
  - ^devise/registrations#create
  - ^devise/registrations#destroy
  - ^devise/registrations#update
  - ^devise/registrations#cancel
  - ^devise/registrations#edit
  - ^devise/sessions#create
  - ^devise/sessions#new
  - ^devise/sessions#destroy
  - ^devise/omniauth_callbacks#passthru
  - ^devise/omniauth_callbacks#failure
  - ^devise/unlocks#create
  - ^devise/unlocks#new
  - ^devise/unlocks#show
  - ^active_storage/direct_uploads#create
ignore_unused_routes:
  - ^cards#update
  - ^cards#update
  - ^cards#destroy
  - ^aws_presigned_posts#create
  - ^nonprofits/donations#show
  - ^nonprofits/cards#show
  - ^nonprofits/cards#update
  - ^nonprofits/cards#update
  - ^nonprofits/supporters#new
  - ^pricing#index
  - ^users#index
  - ^users#create
  - ^campaigns#create_from_template
  - ^webhooks#subscription_payment
  - ^webhooks#stripe
